#! /bin/bash -x

bridge vlan add vid 42 dev eth0
bridge vlan add vid 42 dev eth2
bridge vlan add vid 43 dev eth0
bridge vlan add vid 43 dev eth2
bridge vlan add vid 44 dev eth0
bridge vlan add vid 44 dev eth3
bridge vlan add vid 45 dev eth0
bridge vlan add vid 45 dev eth1
bridge vlan add vid 46 dev eth0
bridge vlan add vid 46 dev eth1
bridge vlan add vid 47 dev eth0
bridge vlan add vid 47 dev eth1
bridge vlan add vid 48 dev eth0
bridge vlan add vid 48 dev eth1
bridge vlan add vid 49 dev eth0
bridge vlan add vid 49 dev eth1
bridge vlan add vid 50 dev eth0
bridge vlan add vid 50 dev eth3
bridge vlan add vid 51 dev eth0
bridge vlan add vid 51 dev eth3
bridge vlan add vid 52 dev eth0
bridge vlan add vid 52 dev eth3
bridge vlan add vid 53 dev eth0
bridge vlan add vid 53 dev eth3
bridge vlan add vid 54 dev eth0
bridge vlan add vid 54 dev eth2
bridge vlan add vid 55 dev eth1
bridge vlan add vid 55 dev eth2
bridge vlan add vid 56 dev eth1
bridge vlan add vid 56 dev eth3
bridge vlan add vid 57 dev eth1
bridge vlan add vid 57 dev eth3
bridge vlan add vid 58 dev eth1
bridge vlan add vid 58 dev eth3
bridge vlan add vid 59 dev eth1
bridge vlan add vid 59 dev eth2
bridge vlan add vid 60 dev eth1
bridge vlan add vid 60 dev eth3
bridge vlan add vid 61 dev eth2
bridge vlan add vid 61 dev eth3
