#!/bin/bash

# Create directories of today and tomorrow to store BGP
# MRT dumps generated by FRRouting. The script is executed
# as part as a cron job every days at midnight.
#    Example:
#    # crontab -u root -l
#    0 0 * * * /root/dir_maker.sh /home/bgp-data >/dev/null 2>&1

if [ "$#" -ne 1 ]; then
  echo "usage: $0 <base_dir>"
  exit 1
fi

BASE_DIR="$1"
DATE_FORMAT="+%Y %m %d"

for time in now tomorrow; do
  curr_date=$(date -d "${time}" "${DATE_FORMAT}")
  read -r -a date_arr <<< "${curr_date}"

  year=${date_arr[0]}
  month=${date_arr[1]}
  day=${date_arr[2]}

  for collect in updates ribs; do
    install -d -g frr -m 775 \
      "${BASE_DIR}" \
      "${BASE_DIR}/${collect}" \
      "${BASE_DIR}/${collect}/${year}" \
      "${BASE_DIR}/${collect}/${year}/${month}" \
      "${BASE_DIR}/${collect}/${year}/${month}/${day}"
  done
done
