#!/bin/bash

VARDIR="/dev/shm/tls_blackhole"

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

function is_root() {
  if [ "${EUID}" -eq "0" ]; then
    return 0
  fi
  return 1
}

function usage() {
    echo "usage: $0 <action> [OPTIONS related to action]"
    echo "  <action> could be:"
    echo "    presetup: should be done at first to generate all config needed for the experiment"
    echo "    ingi: configure & start ingi node"
    echo "      MUST take as OPTIONS: <bird executable> <cert_dir: where to find certs generated by presetup>"
    echo "    bbte: configure & start bbte node"
    echo "      MUST take as OPTIONS: <bird executable> <cert_dir: where to find certs generated by presetup>"
    exit 1
}

function pre_setup() {
  # cert
  local gen_cert="${__dir}/../../../cert-generator/generate_certs.sh"

  # generate certs
  ${gen_cert} "${__dir}" "ingi" ED25519 "ingi.rtr" "130.104.229.94" NULL NULL
  ${gen_cert} "${__dir}" "bbte" ED25519 "bbte.rtr" "198.180.150.60" NULL NULL
}

function setup_all() {
  mkdir -p "${VARDIR}"
}

function check_node() {
  local node="$1"

  if [[ "${node}" != "ingi" && "${node}" != "bbte" ]]; then
    echo "Invalid node ${node}"
    exit 1
  fi
}

function setup_node() {
  local node="$1"

  check_node "$node"

  cp "${__dir}/${node}.conf" ${VARDIR}
  cp "${CERT_DIR}/ca.cert.pem" ${VARDIR}
  cp "${CERT_DIR}/${node}.cert.pem" ${VARDIR}
  cp "${CERT_DIR}/${node}.key" ${VARDIR}

  #${BIRD} -c "${VARDIR}/${node}.conf" -s "${VARDIR}/${node}.sk" -P "${VARDIR}/${node}.pid"
}

function start_bird() {
  local node="$1"
  check_node "$node"

  ${BIRD} -c "${VARDIR}/${node}.conf" -s "${VARDIR}/${node}.sk" -P "${VARDIR}/${node}.pid"
}

function stop_bird() {
  local node="$1"
  check_node "$node"

  kill "$(cat "${VARDIR}/${node}".pid)"
}

case $1 in
  "presetup")
    pre_setup
    ;;
  "setup")
    if [ "$#" -ne "4" ]; then
      echo "usage: $0 setup {ingi|bbte} <bird> <cert_dir>"
      exit 1
    fi

    NODE="${2}"
    BIRD="${3}"
    CERT_DIR="${4}"

    check_node "${NODE}"
    setup_all && setup_node "${NODE}"
    ;;
  "ingi"|"bbte")
    if ! is_root; then
      echo "Please run as root"
      exit 1
    fi

    if [ "$#" -ne 3 ]; then
      echo "usage: $0 {ingi|bbte} <bird> <cert_dir>"
      exit 1
    fi

    BIRD="${2}"
    CERT_DIR="${3}"

    setup_all && \
    setup_node "${1}" && \
    start_bird "${1}"
    ;;
  "start"|"stop")
    if ! is_root; then
      echo "Please run as root"
      exit 1
    fi

    if [ "$#" -ne 3 ]; then
      echo "usage: $0 {start|stop} {ingi|bbte} <bird>"
      exit 1
    fi

    NODE="${2}"
    BIRD="${3}"
    check_node "${NODE}"
    if [ "$1" = "start" ]; then
      start_bird "${NODE}"
    else
      stop_bird "${NODE}"
    fi
  ;;
  *)
    usage
    ;;
esac